package com.hexa.samplejpa.repository;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.hexa.samplejpa.entity.Product;

@Repository
public interface ProductRepository extends JpaRepository<Product, Long> {

	// JPQL
	@Query("SELECT p FROM Product p WHERE p.name LIKE CONCAT('%',:query,'%')OR p.description  LIKE CONCAT('%',:query,'%')")

	List<Product> searchProducts(String query);

	// NativeSQL
	@Query(value = "SELECT p FROM Product p WHERE " + "p.name LIKE CONCAT('%',:query,'%')"
			+ "OR p.description  LIKE CONCAT('%',:query,'%')", nativeQuery = true)
	List<Product> searchProducts1(String query);
	//autogenerated querry
	Product findDistinctByName(String title);
	List<Product> findByNameContaining(String title);
	
	List<Product> findByPriceBetween(BigDecimal  startPrice,BigDecimal endPrice );
	
	List<Product> findByDateCreatedBetween(LocalDateTime startDate,LocalDateTime endDate);
	List<Product> findByNameLike(String name);
	List<Product> findByNameIn(List<String> names);

	List<Product> findProductsByNames(List<String> names);

	
}